# Generated by Django 5.0.6 on 2024-07-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
