# Generated by Django 5.0.6 on 2024-07-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
