# Generated by Django 5.0.6 on 2024-08-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_grupo', models.CharField(choices=[('1a', '1A'), ('1b', '1B'), ('2a', '2A'), ('2b', '2B'), ('3a', '3A'), ('3b', '3B')], max_length=2)),
                ('perfil', models.OneToOneField(limit_choices_to={'tipo_usuario': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('matemáticas 1', 'Matemáticas 1'), ('matemáticas 2', 'Matemáticas 2'), ('matemáticas 3', 'Matemáticas 3'), ('español 1', 'Español 1'), ('español 2', 'Español 2'), ('español 3', 'Español 3'), ('ciencias 1', 'Ciencias 1'), ('ciencias 2', 'Ciencias 2'), ('ciencias 3', 'Ciencias 3')], max_length=20)),
                ('grupo', models.CharField(choices=[('1a', '1A'), ('1b', '1B'), ('2a', '2A'), ('2b', '2B'), ('3a', '3A'), ('3b', '3B')], max_length=2)),
                ('perfil', models.OneToOneField(limit_choices_to={'tipo_usuario': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
    ]
