# Generated by Django 5.0.6 on 2024-08-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alumno_maestro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calificacion2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calificacion3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno')),
                ('materia', models.ForeignKey(limit_choices_to={'perfil__tipo_usuario': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.maestro')),
            ],
        ),
    ]
